import requests
import sys
import subprocess
import os
import re

# --- Definición de códigos de color ANSI ---
VERDE = "\033[92m"
BLANCO = "\033[97m"
ROJO = "\033[91m"
AZUL = "\033[94m"
RESET = "\033[0m"

# --- BANNER SECUNDARIO (con borde de código) ---
print(f"""{VERDE}
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
SSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXSSXSXSSXS
SSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSS
SSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSXS
SXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSSSS
SSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSXSSX
SSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSSSSSS
SSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSXSSXSS
SSXSSSXSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSSSSXSSX
SSSSXSSSSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSXSSSSSSS
SSXSSSSXSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSSSSXSSXSS
SSSSSXSSSXSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSSSXSSXSSXSSSXSSSX
SSXSSSSXSSSSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSXSSSXSS
SSSSXSSSSSXSXSSSXXXXXXXX@XXX@XXXXSSXXXXXXXXX@XXXXXXXSSSXXXXX@XXXXXXXXXXSXSSSXSXXXXXXXXSSXSSSXSSSXXXXXXSXSSSSXSSSXSXXXXXXXSSXSSSSXSSXSXXXXXXXSXSSSSSXSSSXXXXXXSSSXSXXXXXX@XXX@XXXXXXXSSSSXSSSXSSSXSXXXXXX@XXX@XXXSXSSXSSSXSXXXXXSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSSSXSXXXXXSXSSSXSSSXSSSXSSSXSSSXSSSSSSSSSSS
SSXSSSXSSSSSSSXSt%%::.        :%SSXSX;;..        :tSXSSttt:..      ..tSSXXSXSSS%t;::t%@SXSXSSSXS%SS;ttSS@SXSSSSXSSS%t;;;SSXXSXSSSSSSS;;;::;SXSXSXSSSSSSS;;;tX@SXSXS;::.         .;tXXSXSSSXSSSXSX%t;:.       :;tXXXSSSXSSXt%ttt@@SSXSSSSSSXSSSSSSSXSSSSSSSXSSSSSSSXSSSS;t;%SSXSSSSXSSSSSSSXSSSSSSSSXSSXSXSSX
SSSSXSSSXSXSSXXtt8X;.   . ....X8:tSXt%:.. . . ...S:8%S%.8S;:  ..    %8X@XSXXSXXt%ttX88.S8XXSXSXXt @X8 t%SXSSXSXSXS@SXtS8SXSSSXSXSSXS; t;:S8;8SSXSSXXSXX%8t8 :@XXX@%8%.  . . . . :8%X@X@XSXSSXSXX@t :    . ...%88;X@@SXSSXXt ;8 tSS8XXSXSSSSSSXSXSSSSSXSXSSSSSXSXSSXSS@%8S@ :SXXSXSSSSXSXSSSSSXSXSSXSSSSSSSSS
SSXSSSSSSSSSXX@% St888@S%%%SS;S88.%.S;888@S%%%%S% 88%@t.S%888@%%%SX@8%@8.%X8SX88XX@8SSt%@8S@SXXX.XSt%@8@S@SSSSSSSS8@S@8%88tSXSSXSXXX.S%8SX;8888XXXSXSS@@@8t 88@XS8@8%88@%%S%%SS@%S@8;;;S8XXSSSSt:8%;88S%%%S%St;X8t:%SXXS@X8 SSS88XS8XXSXSXSSXSSSSXSSSSSSSXSSSSSSSXXXS888tX@.XXSSSSXSSSSSSXSSSSSSSSSSXSXSSXSS
SSSSSXSXSSXSSX@;XS:X;:.      :t%%SS8S%8 88     :tX%SX@t8X;X;;. .  @.tX@.88@8S@88 8888S88%@@SSXXSS@%t;X8tXXXSXSXX%  tXXS:S@:%@@SXSSXX.X.8S8S%8;8XXSXXSS88@SXX8X8S@88@:@:8t;.   .88%XS%X@XtXXSSX;S.;S;;       %St@@t%8tXSS@X%:8%S888@XXSXSSSSSSSSXSSSXSXSSSSSXSXSSXSXSS88@tS@888X8XSSSXSSXSSSXSXSSXSSSSSSSXSSX
SSXSSSSSSSSSSX@t.%:% 88:@@XX@@@X@8X8S.X8%8@X8XX@@@@X@@t  %% @;S8@S888:8S@88@X888X%888t 8tSX@XS@X;@ StX88X@XXSXS8X8 8S. S S88@@8X@SXX.Xt88XX; 8;8XXSXSXX%;8%t8%8X888S;%8888X@@S8888 tStX%S8S8;8X 8% 88;%8@X8@S 8 %@%88@@S@%88@SS88S@88XX@XXXXSXSXXXXXXSSXSXSSXXXXXXXSS88@%;@XS88@X@X@XXXSSXSSSSSXSSXSXSSSSSSS
SSSSXSSXSXSXSX@%XX.%:8 S@@SXSXX@@X@.%.@ X8@X@SXXSXXSXX;88.%S8:SX@X@8t%8SX88@%X8@ tX@@t  8tS@XS@X:8St;X8SX8XSXSSX8% S.X@%S 888SXXXSXX.X 8%:S8% 88tSXXSS888SXS88t@888X%%X8S@SXXX8S%@8@.@;88@@S  .S:t8.tX@XXXXSSXX8 t%S88@S88S 8SS8;StSSSXXXXS8SSS%X@@X8SSXSSSS%X@@@%@SS8:8SSS8@%XSSSSSX@%8SSXSSXSSSSSSSSXSSXSS
SSXSSSSSSSSSSX@t  t%:88S@XSSSSXSS@SS:XX8;8tX@XXXXXSS@X%  %t 8;%@XS@@;X;@XS.88888S8: @ 8t:88%SX@S:@ S%X;SXXXXSXt X  .X 8XXSX8 XS@XSXX8@ X::S;%t:X:t8@@S%8X@SXX 8SX88XX%X S8SXXSX@SXS8@SX 88 88:8 888@8XSSXSSXSX@%8X .S8%S8t88X8 X S . ...%:%8@Xtt8@@8:t@XSXX%.8S8:8@X8888S@ 8tX:  ...S tXXXSXSSSSXSXSSSSXSSSX
SSSSXSXSSXSSXX@t.X;%%8 X@@XXXXXXX@%88:8%X8:      .tS@@X88.t 8t8@@SS;8 %%;88@S@88:S.S88.8%S8tSX@S%8St%X8tS@SXXS:@S :XS;8X:t:@8SS@XXXX8X8t X8St;S:S88XS88tX@%:8@%@8888%:XS.@XSSXS8XS8%@ S:88@X8.X:8@t@XSSSXSSSX8@%:@ 8 @:%88S @8X..tS@%X888@88SSX8X;XS8%@XXS@S8 @:888S@88XS8t.: tSSS@88S8%@SXXSSXSSSSSXSSSSXSS
SSXSSSSSSSSSSXX%8@ t 8;XXXSXSSXSX@8;S:8@tSSSSS%% 8;S@@%  %%%8:%@@t X .S.8 SX@XX8;@.88.8@t% @888X;@ %SX8@SXXSXS S  %@;%t@X S 8;S8XS@88S S:%8 SXt8 @;@S@%88%S@8t8@888SS%S;XXSSSSXSX88%8S:.@8@8@.@%888SXSXSSXSXSXX%88@%.S.S@t88XX8% 88:@8t@Xt 8t%%8%:% 8;X@SX@X8@%;8@8SX88@X88; S8 SS8:t; 8:tXXXSSSXSSSSXSSSSSS
SSSSSXSXSXSXSX@%  t8%  XXSXXX8.%8@X8X;8X%S%t%tt%8 :%@X%8@.8S  X@8X: t;8  t@8@X88%%.88t;8@t8 8@:t;@ %SX8tS@@X@S8 :t88SXX%8@t;S.@XXX@88X S:@8 ;8X S;S.XS88@8S;88%XX88XStX@;XXSXSXXS@@%; tS ;tXX;tX88@SXSSSSXSSSX@%8;%t%S% @8%.88:X8888X@8X:X%X.%.8S:%%8%8@XX@@8 @;88;%X88X@8;@;:SX8X%.S;Xt@:XXSXSSSSXSSSSXSSXS
SSXSSSSSSSSSSX@%:X;88888X8888S88XXS8S X ;8.%XS@XX@SS8@%  8SX88@88@;X8t%%@@@@SX8@ @.88tXt;S:@.@.;:@%;SS8SX@@SX@@ 8%8X8;tSS;t@ 88@XX@@;X8%S88.SX8@.@:@8%.88;8@X.8X88@SStX SXSXSSXXXXXt8X XXSt8@t%S.XXXSSSXSSSXSXXX888t% 8X@;88X8 88t@XS%8@8:%%8% @S:% 8XXXSXX;8S%;8@8XX88@;S@88XS@XSS88S@@X8S@SSXSXSSSXSSSXSSS
SSSSXSSXSSXSSX@%XS:8t:;@@X@SS.888@@:S.X@88@@888888@@@@t88 8S tSt %%X88888XXX%%88 X.888@@t8@ X;8;8X %SX8@X8Xt.@ 88%  %%  SS88SS8tSX88:X @ S@X8Xt;XSX X@8%.8%.888S888XS;X8%@XSSSSXSXX%8 ;t@@88:@SX%.XSXSSSSXSSS@X%.8SSt8:S@8X:8tX88:S@@XX8X%S 8888%.%S88X@SX@S8St%88tXX88S%t@:X@S@SSSXX SSS888S8X@SXSXSSXSSSSX
SSXSSSSSSSSSXX@t %.;.8tS@@XS88@SX@S8S8%XX8.SXXSSSXXSXXS  %: 88S8@8;%; 888S@@XX88St.8;X8X@88 ;X;88%.t%X.SX@X:@.8t@%::;:%:;%@8X:S8;SXX.X S:;8@S8Xt S 8.;%;8%X@888%888SX%X.8XS@SSXXSS@t@.S:8;88@.8:888XXXSXSSXSXXX;8S SX8;X@t88@XS88tS8XX%88.XS8;.X tX 8.X@SX@X8 S:888XX88X%;XS.@@X@SS%.@%%;t:@S@@XXSSSSSSSSXSS
SSSSXSXSXSXSSX@;@X.%.8:S@XX@8X@@SX@8X:XX88t@8X@XXSSXX@;8@.S 8;X8S%8.%t 8 %@@SX88 @;88S@SXXX8 t;.t8;ttS8t@8@.S;X.X8       ;88tS.@;X8X8@ X:@8:X8@S%8@ 8@. :S8S888S888XX%@8t@@X8XX@S@88%;X88;S;8 X;8t8%8X8XXXSSSXX:8 S.88:S88S @SX88@X@XS8X8 S 8888@ S 8S8@XXXX8S;%8.t@X8:8XtS88XXSXXX88X%X 88;XSXXSSXSXSSXSSSS
SSXSSSSSSSSSSXXS  t%.88%XXSSXSXXXXS8S %XX8SX8@XXXXXXX@t  8. 8t%@@%;8 S;:88@88S88 X:8t@XX8XX%@@ @888t:X8@S888 8tS88@8SSSX8@88StXS8S8t8SSXS88tS8XXXXt@ XSS888X88:SX88@%:X.8XX8@XS;:88% SS8X@@X:8 :%X8@@X8@XX@XS; X %tt88;88t88@X.8:8S@@SX8X.XS88:8@ 8 8XS8@XX8X:8t88:%%888t@X8 @X8@Xt @ XS8t%@X@@@XSSSSXSSSSXS
SSSSSXSSXSSXSX@t8 SS.8;SXXSSS@S@XX88S;@.88.:;:::;;SX@S;8X S 88XX@S88  %X:88StX88St.88SXXSXS@8.X.8888;@.:%88@ S 88X8S8X@8@SSt8 @:88t%:8 S ::XS8@SXXX888.8SS8888@%88@8XS 8%;;;t; SX %;t88X88@XX88XtSt88...::;; @:t%:S:.X@8888%X%S88%X@XSS88 SS88.88X@%S88.: 8S;88;8888S88X%8: @;..;;8 .% 88t@XXXSXSXXSSSSXSSSS
SSXSSSSSSSSSSX@;8X:@ 8:S8XXSXS@XX@%8S88X :  ;:::;@ 8SXSS%:@%8.%X@X@XS%SS%@@8;888t8;8;8SXS@XXS%8@S%@@t@@:t8 .@t@8;8S8SSSSSX8@: X@:8.88@8S.88;X8@@XXSX88 8X88@t%8X888@88t   t:;.:;: S8 SX8S@SXXXS888tS8S .:::  ;%;;8.;X88XS%8S@@S88tS@@S8X8 X %%@;88%8%    : .8X8S@88SX88@S88;:. ..  8t 8%:SSXSSSXXSSXSSSSSXSS
SSSSXSXSSXSXSXX%tS  S88X8XSSXSX@X@8;@ SX@8;SSSXX%t888S; S  @8;8X@@XS;t88%; 888.88.X88@@SSXX@S@%88S;t%@8S;8@  ;8.S@8SSSXSXXX%:8S; 88t88S %S8;X@XSSSSXS%8X.%;@:88888@@ 8%8:%SSSS%;:8.%@XS@X8@8@XS@888 %@SSSSSS%%;@;tSXXX@X@88@ :%8.SX@X%X88 .t8@XS%.X X@S%St: %;%%88:%S8X% ....;%XX%%t;8XSXXSSSXSSSSSSXSXSSSXS
SSXSSSSSXSSSSXXS%SXt;XX88X@SSSXXXS@SS8;.         ;;;SSS%8X%tX@S8XXXXSSX@t;;S%%S@.;SXSX@X@X8XXSXS%t:.;X@tSX%S.tS%SXSSXSSSSS@SSS%%t;t;88S;X%XXXXXXSSX@@@SX; t%XSX8@S8%t:        .t%%X@XXXXXXSSXXXSX8%:...       ;SSS@XXXSSS%@X@:%t8X@XXXX8X% %SS@8Xtt;.:   .;;:t:.%%888%;%:t;.       .:SS8X@XSSSSXSXSSSSSSXSSS
SSSSSXSSSSSXSSXX@8XS8@@8SXXXXSXSX@X@8XXS8XXSXSSXX@@XX8@@88X@XXXXSSSXX@SX@X@@X@@XX@X@@@@X8@@SXXXXX@@@XX@@SXX@8XSXSXSSSSXSXSXXX@XX@@X@8@8@@@S8S@SSXSXX8@8X8X@@XXX8@X@@8XXXXSSSSXXX88X8X8XXSXSXXSXSSSX@XXXSSSSSS@@8XXXSXX@X8XX8@@@@88XSXXSX@@XX88X@S8X@@SSSXX@X@@XX@@@@@@XXX@@XXXXS@SXS8@8XXSXXSSXSSSXSSXSSSSSX
SSXSSSSXSSXSSSSXSXXXXSSXXXXXXSXSSXSXX@X@XXXXSXXSXSXSSSSXSXXXXXXSSXSXXXXS@8XXXSXXXX@S@XX8XXSXSSSSXX@XXSSXXXXSXXSSXSXSXSSSSSSSSXS@XXXS@XSXXXSXXS@XSXSSXSX8X@XXXX8SXSXXXXXXXXXXXXXXX@@XXSXXXSXSXSSXSSXXSXSXXXXXXXXXXSSSXSXXSXSXSSXXXSSSSXXXXSXXXXXX8X@XXXXXXXSXXXSXXXXXSXXXXXXXXS@8XXXXXXSSX@XXSXSSSSSXSSSXSSSS
SSSXSSXSSSSSXSSSSSXSSSXSSXXXSSSXSSSSSSXSSSSSXSSSSXSSXSSXSSSSSSSXSSSXSXXSSXSSSXSSSSXXSXXSSX@SXSXSSSSSSX@SSSSSSXSSSSSSSSXSXSSXSSSSSS@X@XXSSXXSX@SXSSXSSXSXSSSSSSSXSSXXSSSSSSSSSSSXXX@S8XSXX@XXSSXSSXSSSSSSSSSSSXSXSSXSSSXXXXSSXSSXSXSXSSSSSSXXXS8X@S@XXXXSSSXSSSSXSXSX@XXSSSSSSSSXXSXXSXSSSXSSSSSXSXSSSSSSSXSS
SSSSSSSSXSSSSSXSXSSSXSXSSSSSSXSSSXSSXSXSXSSSSSXSSSSSSSXSXSXSXSSSSXSXSSSXXSSXSSXSSSXSSSSXSSXXSSSXSSXSSSXSSXSXSSXSSXSXSSSSSSXSSXSSXSXXXSSXSSSXXXSSXSSXSXXSXSSSSSXSSXSSSXSXSXSSXSSXSXX@XSSXXSS@XSSSSSXSSXSXSSXSSSSSXSSSXSXSSXSSSXSSSSSSSXSSXSSSXXX@S@XXSXX@XSSXSXSXSSSXXSSXSSSXSSXSSSSXSSSXSXSXSXSSSSSSXSXSSSXS
SXSSXSSSSXSXSSSSSSXSSSSXSXSXSSSXSSSXSSSSSXSXSSSXSXSXSSSSSSSSSXSXSSSSXSSSXSSSXSSSXSSXSSXSSSXSSXSSSSSXSSSSXSSSSSSXSSSSSXSSXSSSSSSXSSSSXSSSSXSXSSXSSSSSSSSSSSXSXSSXSSSSXSSSSSXSSSSXXSXSSSXXX@XSXSXSSSSXSSSSXSSSXSXSSSXSSSXSSSXSSSSSXSXSSSXSSSSXSSSSSSSSSXSSXXSSSSSSXSSSXSSSSXSSSXXSSXSSXSSSSXSSSSSXSSXSSSSSXSSS
SSSXSSXSSSSSSXSSXSSSXSSSSSSSXSSSSXSSXSXSSSSSXSSSSSSSXSXSSXSSSSSSSXSSSSXSSSXSSSXSSSSSSXSSXSSXSSSXSXSSXSSSSSXSXSSSSXSSXSSSSSXSSXSSSSXSSXSXSSSSSSSSXSXSXSSXSSSSSXSSXSSXSSXSXSSSXSXSSSXSXSSXSSXXSSSXSXSSSXSSSSXSSSSSXSSSXSSSXSSSXSSXSSSXSSSSXSSSSXSSXSXSSXXXSSXSSSXSSSXSSXSXSSSXSSSXSSSSSXSXSSXSXSSSSSSSXSSXSSSX
SSSSSSSXSSXSSSSXSSSSSSXSXSXSSSXSSSSSSSSXSSXSSSXSXSSSSSSXSSSXSXSXSSXSSXSSXSSSXSSSXSXSSSSSSXSSSXSSSSSSSXSXSSSSSSXSSSXSSSXSSSSSXSSSXSSSSSSSSXSXSXSSSSSSSXSSSXSXSSSSSXSSSSSSSSXSSSSXSSXSSSSXXSSSSXSSSSSXSSSXSSSSXSXSSSSSSSXSSSXSSSSSSXSSSXSSSXSSSSXSSSSXSSXS@SSSXSSSXSSSXSSSSXSSSXSSSXSXSSSSSSSSSSXSXSSSSSSSSXSS

{RESET}""")
# --- FIN BANNER ---

# Función para buscar nombres de usuario
def buscar_usuario(username):
    sitios_encontrados = []
    
    try:
        with open("sitios_usuarios.txt", "r") as f:
            lineas = f.readlines()
    except FileNotFoundError:
        print(f"[!] El archivo '{BLANCO}sitios_usuarios.txt{RESET}' no se encontró.")
        return []
        
    for linea in lineas:
        nombre_sitio, url_base = linea.strip().split(',')
        url_perfil = url_base + username
        
        try:
            response = requests.get(url_perfil, timeout=5)
            if response.status_code == 200:
                print(f"{VERDE}[+] Usuario '{username}' ENCONTRADO en {nombre_sitio}{RESET}")
                sitios_encontrados.append(url_perfil)
            else:
                print(f"{ROJO}[-] Usuario '{username}' NO ENCONTRADO en {nombre_sitio}.{RESET}")
        except requests.exceptions.RequestException:
            print(f"[!] {BLANCO}Error al conectar{RESET} con {nombre_sitio} para '{username}'.")
    
    return sitios_encontrados

# Función para buscar correos electrónicos usando Holehe
def buscar_correo(email):
    print(f"[*] Usando la herramienta {VERDE}Holehe{RESET} para buscar el correo: {email}")
    print("---")
    
    # --- Nuevo: Verificación de formato de correo ---
    if "@" not in email or "." not in email:
        print(f"{ROJO}[!] ERROR:{RESET} El formato del correo electrónico es incorrecto. Por favor, ingresa una dirección válida.")
        return # Salimos de la función si el formato es inválido

    try:
        proceso = subprocess.run(['holehe', email], capture_output=True, text=True, check=True)
        salida_holehe = proceso.stdout
        
    except FileNotFoundError:
        print(f"\n{AZUL}[*] Herramienta Holehe no encontrada. Iniciando instalación automática...{RESET}")
        try:
            subprocess.run(['pip', 'install', 'holehe', '--break-system-packages'], check=True)
            print(f"{VERDE}[+] Instalación de Holehe completada. Reejecutando la búsqueda...{RESET}\n")
            proceso = subprocess.run(['holehe', email], capture_output=True, text=True, check=True)
            salida_holehe = proceso.stdout
            
        except subprocess.CalledProcessError as e:
            print(f"\n{ROJO}[!] ERROR de instalación:{RESET} pip devolvió un error. Asegúrate de que tienes 'pip' instalado.")
            return

    lineas = salida_holehe.split('\n')
    urls_registradas = []
    
    for linea in lineas:
        if "Registered" in linea or "Exists" in linea:
            match = re.search(r'https?://[a-zA-Z0-9.-]+', linea)
            if match:
                urls_registradas.append(match.group(0))

    print(f"\n{VERDE}Correo registrado en:{RESET}")
    if urls_registradas:
        for url in urls_registradas:
            print(f"{VERDE}  - {url}{RESET}")
    else:
        print(f"{BLANCO}  - No se encontró registro en sitios populares.{RESET}")
    
    print(f"\n{BLANCO}--- Salida completa de Holehe ---{RESET}")
    print(salida_holehe)
    
# Función para rastrear IPs
def track_ip(ip_address):
    print(f"[*] Rastreo de IP en progreso para: {AZUL}{ip_address}{RESET}")
    print("---")
    
    try:
        response = requests.get(f"http://ip-api.com/json/{ip_address}", timeout=5)
        data = response.json()
        
        if data['status'] == 'success':
            print(f"{VERDE}[+] Información de IP encontrada:{RESET}")
            print(f"  - País: {data.get('country')}")
            print(f"  - Ciudad: {data.get('city')}")
            print(f"  - Región: {data.get('regionName')}")
            print(f"  - ISP: {data.get('isp')}")
            print(f"  - Organización: {data.get('org')}")
            print(f"  - Latitud/Longitud: {data.get('lat')}, {data.get('lon')}")
            
        else:
            print(f"{ROJO}[-] No se pudo obtener información para la IP: {ip_address}{RESET}")
            print(f"{BLANCO}Mensaje de error: {data.get('message')}{RESET}")
    
    except requests.exceptions.RequestException:
        print(f"{ROJO}[!] Error al conectar con el servicio de rastreo de IP.{RESET}")

if __name__ == "__main__":
    try:
        if len(sys.argv) < 3:
            print("Uso: python main.py <opcion> <argumento>")
            print("Ejemplo: python main.py --user anthonydominguez")
            print("Ejemplo: python main.py --email anthonydominguez@gmail.com")
            print("Ejemplo: python main.py --ip 8.8.8.8")
            sys.exit(1)
        
        opcion = sys.argv[1]
        argumento = sys.argv[2]
        
        if opcion == "--user":
            buscar_usuario(argumento)
        elif opcion == "--email":
            buscar_correo(argumento)
        elif opcion == "--ip":
            track_ip(argumento)
        else:
            print("Opción inválida. Usa --user, --email o --ip.")
            sys.exit(1)

    except KeyboardInterrupt:
        print(f"\n{ROJO}[!] User Keyboard Interrupt{RESET}")
        sys.exit(1)
